---

- name: Run bga ranking database
  docker_container:
    name: bga-ranking-database
    pull: yes
    image: postgres:11.1
    state: started
    recreate: "{{ DB_RECREATE }}"
    ports:
      - "{{ BGA_DB_PORT }}:5432"
    env:
      POSTGRES_USER: "{{ BGA_DB_USER }}"
      POSTGRES_PASSWORD: "{{ BGA_DB_PWD }}"
      POSTGRES_DB: "{{ BGA_DB_NAME }}"

- name: Launch RGA back
  docker_container:
    name: bga-ranking-back
    pull: yes
    image: "slonepi/bga-ranking-back:{{ BGA_APP_VERSION }}"
    state: started
    recreate: yes
    ports:
      - "8093:8080"
    env:
      DATABASE_HOST: "bga-ranking-database"
      DATABASE_USER: "{{ BGA_DB_USER }}"
      DATABASE_PASSWORD: "{{ BGA_DB_PWD }}"
      DATABASE_NAME: "{{ BGA_DB_NAME }}"
      DATABASE_PORT: "5432"
    links:
      - bga-ranking-database
